version: '3.4'

services:
  postgres:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    environment:
      POSTGRES_USER: statistics
      POSTGRES_PASSWORD: statistics
      POSTGRES_DB: statistics
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5682:5672"
      - "15682:15672"

  zookeeper:
    image: qnib/plain-zookeeper:2018-04-25
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_CREATE_TOPICS=common:1:1
